apiVersion: v1
kind: ConfigMap
metadata:
  name: journal-config
  namespace: journal-app
data:
  FLASK_ENV: "production"
  FLASK_APP: "app"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"
  LOG_LEVEL: "INFO" 