"""Initial migration

Revision ID: 3fb8addcd36a
Revises: 
Create Date: 2025-05-11 15:29:39.776864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb8addcd36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalentrys',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journalentrys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journalentrys_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalentrys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journalentrys_title'))

    op.drop_table('journalentrys')
    # ### end Alembic commands ###
